POST http://localhost:3000/api/registration
Content-Type: application/json

{
  "email": "skeet@gmail.com",
  "password": "password"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "wolsky@gmail.com",
  "password": "password"
}
### 
POST http://localhost:3000/api/logout
###
GET http://localhost:3000/api/refresh
###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndvbHNreUBnbWFpbC5jb20iLCJpZCI6IjY0YjE2NDZkY2IzNTRmMzM1M2VhNGJjMCIsImlhdCI6MTY4OTM1ODk4MCwiZXhwIjoxNjg5MzU4OTk1fQ.-QFGpNVfK7wcm6QYYjjtJ67fLKQmIGldIf1ZDVpj35w